NUPLAN_DATA_ROOT: "/media/kemove/BigSSD/gjc/SimScale"
NUPLAN_DB_FILES: "/media/kemove/BigSSD/gjc/SimScale"
NUPLAN_SENSOR_ROOT: "/media/kemove/BigSSD/gjc/SimScale/openscene_camera/openscene-v1.1/sensor_blobs"
NUPLAN_MAPS_ROOT: "/media/kemove/BigSSD/gjc/SimScale/maps"
NUPLAN_MAP_VERSION: "nuplan-maps-v1.0"
